// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj4-U1opI7DXNI2N_clglrfcmJHxCsebU',
    appId: '1:982793571503:android:0d2383f97190d1a6b8185a',
    messagingSenderId: '982793571503',
    projectId: 'dailylingo-pbb',
    storageBucket: 'dailylingo-pbb.firebasestorage.app',
  );
}
